<<<<<<< HEAD
name = "srmplanner"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "example.com", zone_name = "example.com" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts"]

[[build.upload]]
format = "service-worker"
=======
name = "srm-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "29fd27cbfe2b4a52b281f813349a9cd0"
>>>>>>> a7450610e6b674eadf9ff8950c7bcf6c259158ab
